### ISSUE TITLE
'Access-Control-Allow-Origin' CORS goiburua aktibatu

### ISSUE THREAD

**Issue by Sergiop79** [erral/eitbapi#21]
Kaixo

Lehendabizi mila esker Eitb API hau garatzeagatik.

Ederto egongo litzateke ` 'Access-Control-Allow-Origin' : '*' ` CORS  HTTP goiburua aktibatzen bada. Nabigatzaile batetik Ajax eskaerak egin ahal izateko.

Web aplikazio bat egin dut API hau erabilita https://sergiop79.github.io/eitbjs/ eta orain arte https://crossorigin.me/ izeneko zerbitzu bat erabiltzen nuen Api-ari eskaerak egiteko. Zeren bestela ezinezkoa zen erantzun bat jasotzea. 

Nabigatzaileek honelako mezu bat jartzen dute Ajax eskaera bat egiterakoan:

`Jatorri gurutzatuaren eskaera (CORS) blokeatuta: jatorri bereko politikak ez du baimentzen https://crossorigin.me/http://still-castle-99749.herokuapp.com/playlist helbideko baliabidea irakurtzea. (Arrazoia: 'Access-Control-Allow-Origin' CORS goiburua falta da).`

Baina azken aldian `crossorigin.me` ez dabil ondo.

Ez dut Pyramid kontrolatzen, baina saiatuko nintzateke  Goiburu hori konfiguratzen.

Ondo iruditzen zaizu hau inplementatzea? agian ez zaizu ideia ona iruditzen ...

Eskerrikasko

Sergio Peña

**Comment by erral** [comment]
Bai, ideia ona da. Orain arte ez neukan jarrita nik APIa erabiltzen dudan
lekuan (kodi pluginean) behar ez nuelako.

Baina bihar goizean bertan aktibatuko dut CORS goiburua.

--
Mikel Larreategi
CodeSyntax
+34 943821780

2017 urr. 29 14:17 erabiltzaileak hau idatzi du ("Sergio Peña" <
notifications@github.com>):

Kaixo

Lehendabizi mila esker Eitb API hau garatzeagatik.

Ederto egongo litzateke 'Access-Control-Allow-Origin' : '*' CORS HTTP
goiburua aktibatzen bada. Nabigatzaile batetik Ajax eskaerak egin ahal
izateko.

Web aplikazio bat egin dut API hau erabilita https://sergiop79.github.io/
eitbjs/ eta orain arte https://crossorigin.me/ izeneko zerbitzu bat
erabiltzen nuen Api-ari eskaerak egiteko. Zeren bestela ezinezkoa zen
erantzun bat jasotzea.

Nabigatzaileek honelako mezu bat jartzen dute Ajax eskaera bat egiterakoan:

Jatorri gurutzatuaren eskaera (CORS) blokeatuta: jatorri bereko politikak
ez du baimentzen https://crossorigin.me/http://still-castle-99749.herokuapp.
com/playlist helbideko baliabidea irakurtzea. (Arrazoia:
'Access-Control-Allow-Origin' CORS goiburua falta da).

Baina azken aldian crossorigin.me ez dabil ondo.

Ez dut Pyramid kontrolatzen, baina saiatuko nintzateke Goiburu hori
konfiguratzen.

Ondo iruditzen zaizu hau inplementatzea? agian ez zaizu ideia ona iruditzen
...

Eskerrikasko

Sergio Peña

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/erral/eitbapi/issues/21>, or mute the thread

**Comment by erral** [comment]
Begiratu mesedez ea ondo dabilen edo goiburu gehigarririk behar duzun.

**Comment by Sergiop79** [comment]
Ederto, goiburu horrekin nahikoa da. Orain primeran dabil. Eskerrikasko
